name: Backend CPP

on:
  push:
    paths:
      - 'backend-python/**'
  workflow_dispatch:

env:
  SERVICE: backend-python


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{secrets.DOCKER_HUB_USER}}
          password: ${{secrets.DOCKER_HUB_PWD}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./${{ env.SERVICE }}/
          file: ./${{ env.SERVICE }}/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USER }}/${{ env.SERVICE }}:${{ github.sha }}
